### ISSUE TITLE
Edit / Delete Migration

### ISSUE THREAD

**Issue by amitgoyal** [joshirohit100/migration_glue#22]
We should have functionality to Edit / Delete the migration once it is created.

Most of the time, we keep editing the Migration to make fixes, adjust as per the new changes etc.

Scenario - Let's say we have created Users migration and then based on our various Content types migration on Users. Now if we need to make some fixes then we have to create new Users migration which means we may need to create all Content types migration again as those are based on Users.

cc: @joshirohit100, @pranitjha

**Comment by joshirohit100** [comment]
PR for edit migration - https://github.com/joshirohit100/migration_glue/pull/35

**Comment by joshirohit100** [comment]
PR is merged.
