### ISSUE TITLE
Run migration compatibility with latest version of Migration Tools module

### ISSUE THREAD

**Issue by amitgoyal** [joshirohit100/migration_glue#32]
When we are trying to run migration using user interface with latest version of migrate_tools (migrate_tools 8.x-4.0) module then it shows error.

So far now, we have added the dependency for older version on migrate_tools (migrate_tools 8.x-4.0-rc1) module into migration_glue.info.yml.

cc: @joshirohit100, @pranitjha

**Comment by joshirohit100** [comment]
closing as done in https://github.com/joshirohit100/migration_glue/pull/66
